version: "3"

networks:
  network:
    driver: bridge
services:
  events:
    image: sphadnis09/events:latest
    volumes:
      - /tmp:/tmp
    networks:
      - network
    restart: always
    environment:
      MONGO_SERVER: "mongodb"
      DATABASE: "eventbrite"
      COLLECTION: "events"
    ports:
      - 3000
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    networks:
      - network
    environment:
      MONGODB_DATABASE: eventbrite   
    ports:
      - 27017:27017
    restart: always
  proxy:
    image: eeacms/haproxy
    depends_on:
    - events
    ports:
    - "3000:5000"
    environment:
      FRONTEND_PORT: "5000"
      BACKENDS: "events"
      BACKENDS_PORT: "3000"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"
      HTTPCHK: "GET /ping"
    networks:
      - network
volumes:
  schemas:
    external: false


