apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
spec:
  selector:
    matchLabels:
      app: events
  replicas: 2
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - name: events
        image: sphadnis09/events:v10
        ports:
        - containerPort: 3000
        env:
        - name: SERVER
          value: "3.210.40.136"
        - name: DATABASE
          value: "eventbrite"
        - name: COLLECTION
          value: "events"
---
apiVersion: v1
kind: Service
metadata:
  name: events
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: events

